language: minimal
services:
- docker
script:
- docker run -v "$TRAVIS_BUILD_DIR":/postfacto postfacto/postfacto:node11 /bin/bash -c "cd
  /postfacto && npm config set user 0 && npm config set unsafe-perm true && ./deps.sh && ./test.sh && ./package.sh"
