apiVersion: v1
kind: Service
metadata:
    name: "postfactoal-3469"
    labels:
        app: "postfactoal-3469"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "postfactoal-3469"