development:
  adapter: mysql2
  database: retro_app_development
  pool: 5
  host: 127.0.0.1
  port: 32768
  user: root
  password: secret

test:
  adapter: mysql2
  database: retro_app_test
  pool: 5
  host: 127.0.0.1
  port: 32768
  user: root
  password: secret
