on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: altest2.azurecr.io
        username: ${{ secrets.acr_altest2_username }}
        password: ${{ secrets.acr_altest2_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t altest2.azurecr.io/postfactoal:${{ github.sha }}
        docker push altest2.azurecr.io/postfactoal:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_postfactoal_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep postfactoal4c9a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace postfactoal4c9a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: postfactoal4c9a
        container-registry-url: altest2.azurecr.io
        container-registry-username: ${{ secrets.acr_altest2_username }}
        container-registry-password: ${{ secrets.acr_altest2_password }}
        secret-name: postfactoaldockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: postfactoal4c9a
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          altest2.azurecr.io/postfactoal:${{ github.sha }}
        imagepullsecrets: |
          postfactoaldockerauth